# Generated by Django 3.1.4 on 2020-12-26 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='default.png', upload_to='media')),
                ('related_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=200)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('related_operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='main.operation', verbose_name='Cards')),
            ],
            options={
                'ordering': ['published'],
            },
        ),
        migrations.CreateModel(
            name='BankCalculation',
            fields=[
                ('time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instution_title', models.CharField(max_length=200, verbose_name='Instution')),
                ('document_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment', models.CharField(max_length=150, verbose_name='Appointment')),
                ('income_1', models.PositiveIntegerField(verbose_name='Income_1')),
                ('income_2', models.PositiveIntegerField(verbose_name='Income_2')),
                ('expense', models.PositiveIntegerField(verbose_name='Expense')),
                ('expense_1', models.PositiveIntegerField(verbose_name='Expense_1')),
                ('expense_2', models.PositiveIntegerField(verbose_name='Expense_2')),
                ('expense_3', models.PositiveIntegerField(verbose_name='Expense_3')),
                ('expense_4', models.PositiveIntegerField(verbose_name='Expense_4')),
                ('expense_5', models.PositiveIntegerField(verbose_name='Expense_5')),
                ('expense_6', models.PositiveIntegerField(verbose_name='Expense_6')),
                ('expense_7', models.PositiveIntegerField(verbose_name='Expense_7')),
                ('expense_8', models.PositiveIntegerField(verbose_name='Expense_8')),
                ('expense_9', models.PositiveIntegerField(verbose_name='Expense_9')),
                ('expense_10', models.PositiveIntegerField(verbose_name='Expense_10')),
                ('expense_11', models.PositiveIntegerField(verbose_name='Expense_11')),
                ('expense_12', models.PositiveIntegerField(verbose_name='Expense_12')),
                ('related_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='main.card', verbose_name='Operations')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
