# Generated by Django 3.1.4 on 2020-12-28 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_bankcalculation_document_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcalculation',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
