# Generated by Django 3.1.4 on 2020-12-29 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201229_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcalculation',
            name='related_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='main.card', verbose_name='Operations'),
        ),
    ]
