# Generated by Django 3.1.4 on 2020-12-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201229_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense',
            field=models.PositiveIntegerField(blank=True, verbose_name='Expense'),
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_1',
            field=models.PositiveIntegerField(blank=True, verbose_name='Expense_1'),
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_10',
            field=models.PositiveIntegerField(blank=True, verbose_name='Expense_10'),
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_11',
            field=models.PositiveIntegerField(blank=True, verbose_name='Expense_11'),
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_12',
            field=models.PositiveIntegerField(blank=True, verbose_name='Expense_12'),
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_2',
            field=models.PositiveIntegerField(blank=True, verbose_name='Expense_2'),
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_3',
            field=models.PositiveIntegerField(blank=True, verbose_name='Expense_3'),
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_4',
            field=models.PositiveIntegerField(blank=True, verbose_name='Expense_4'),
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_5',
            field=models.PositiveIntegerField(blank=True, verbose_name='Expense_5'),
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_6',
            field=models.PositiveIntegerField(blank=True, verbose_name='Expense_6'),
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_7',
            field=models.PositiveIntegerField(blank=True, verbose_name='Expense_7'),
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_8',
            field=models.PositiveIntegerField(blank=True, verbose_name='Expense_8'),
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_9',
            field=models.PositiveIntegerField(blank=True, verbose_name='Expense_9'),
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='income_1',
            field=models.PositiveIntegerField(blank=True, verbose_name='Income_1'),
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='income_2',
            field=models.PositiveIntegerField(blank=True, verbose_name='Income_2'),
        ),
    ]
