# Generated by Django 3.1.4 on 2020-12-29 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201229_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcalculation',
            name='instution_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Instution'),
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
