# Generated by Django 3.1.4 on 2020-12-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201229_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcalculation',
            name='appointment',
            field=models.CharField(blank=True, default=True, max_length=150, verbose_name='Appointment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Expense'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_1',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Expense_1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_10',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Expense_10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_11',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Expense_11'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_12',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Expense_12'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_2',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Expense_2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_3',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Expense_3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_4',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Expense_4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_5',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Expense_5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_6',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Expense_6'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_7',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Expense_7'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_8',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Expense_8'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='expense_9',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Expense_9'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='income_1',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Income_1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='income_2',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Income_2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcalculation',
            name='instution_title',
            field=models.CharField(blank=True, default=True, max_length=200, verbose_name='Instution'),
            preserve_default=False,
        ),
    ]
