# Generated by Django 3.1.4 on 2021-01-01 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201229_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCalculationHeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.CharField(max_length=20, verbose_name='Num1')),
                ('num2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Num2')),
                ('num3', models.PositiveIntegerField(blank=True, null=True, verbose_name='Num3')),
                ('num4', models.PositiveIntegerField(blank=True, null=True, verbose_name='Num4')),
                ('num5', models.PositiveIntegerField(blank=True, null=True, verbose_name='Num5')),
                ('num6', models.PositiveIntegerField(blank=True, null=True, verbose_name='Num6')),
                ('num7', models.PositiveIntegerField(blank=True, null=True, verbose_name='Num7')),
                ('num8', models.PositiveIntegerField(blank=True, null=True, verbose_name='Num8')),
                ('num9', models.PositiveIntegerField(blank=True, null=True, verbose_name='Num9')),
                ('num10', models.PositiveIntegerField(blank=True, null=True, verbose_name='Num10')),
                ('num11', models.PositiveIntegerField(blank=True, null=True, verbose_name='Num11')),
                ('num12', models.PositiveIntegerField(blank=True, null=True, verbose_name='Num12')),
                ('num13', models.PositiveIntegerField(blank=True, null=True, verbose_name='Num13')),
                ('num14', models.PositiveIntegerField(blank=True, null=True, verbose_name='Num15')),
                ('related_bank_operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bankcalculation')),
            ],
        ),
    ]
