# Generated by Django 3.1.4 on 2021-01-01 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210101_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcalculationheaders',
            name='related_bank_operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bankcalculation'),
        ),
    ]
